# name: Test container

# on:
#   pull_request:
#   push:
#     branches: [main]
#   # to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   test-container:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout repository content
#         uses: actions/checkout@v4 # Checkout the repository content to github runner.

#       - name: Build and run dev container tests
#         uses: devcontainers/ci@v0.3
#         with:
#           runCmd:
#             # cmds from inside container
#             make all
