name: Build, install, lint, test and format

on:
  pull_request:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  install_lint_test_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.

      - name: Build and install dev container
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ghactions/devcontainer.json
          runCmd:
            make install
            
      - name: Lint files
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ghactions/devcontainer.json
          runCmd:
            make lint

      - name: Test packages
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ghactions/devcontainer.json
          runCmd:
            make test

      - name: Format files
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ghactions/devcontainer.json
          runCmd:
            make format